services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${CONTAINER_PORT}
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    environment:
        # По ТЗ
        # Но про Flask написали только в 5 пункте, а я уже все сделал на FastAPI
      - FLASK_ENV=${APP_ENV}
        # Для FastAPI
      - APP_ENV=${APP_ENV}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
    volumes:
      - ./scripts/server-info.sh:/app/server-info.sh:ro
    healthcheck:
      test: ["CMD", "bash", "/app/server-info.sh", "http://localhost:${CONTAINER_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: always
